image: z5y1f1y8/gradle:7.4.2-jdk11

before_script:
  # caching rely on this to be defined, otherwise it goes to user home
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

variables:
  # speed up checkout of the wls
  GIT_STRATEGY: fetch
  GIT_DEPTH: 10
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  # should be overwritted at project level
  PUBLISHED_VERSION: 1.2-SNAPSHOT


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  before_script:
    - USING_PROXY=true source ./.build_env
  script:
    #- curl -v -s https://gitlab.com/gitlab-org/incubation-engineering/mobile-devops/download-secure-files/-/raw/main/installer | bash
    - ./gradlew --build-cache clean build
    - ls -altr build/distributions
    - ./gradlew --build-cache publish
  #artifacts:
  #  untracked: false
  #  when: on_success
  #  expire_in: 30 days
  #  paths: ["build/distributions/OCIPluginForIntelliJ-1.0.2.zip"]

#deploy-to-artifactory:
#    stage: deploy
#    rules: 
#      - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
#    before_script:
#    - USING_PROXY=true source ./.build_env
#    script:
    # -  ./gradlew --build-cache publish